version: "3.9"

x-node-command: &node-command
  command: bash -c
          "cat /etc/os-release | grep PRETTY_NAME | cut -d'=' -f2;
          echo node `node -v`; 
          echo npm `npm -v`;
          echo yarn `yarn -v`; 
          echo pnpm `pnpm -v`;"

x-wait-command: &wait-command
  command: bash -c 
          "while sleep 1000; do :; done;"

services:
  dev:
    <<: [*wait-command]
    image: ghcr.io/armando-fandango/ezdev/ezdev:0.9-node-alpine-dev
    volumes:
      - .:/workspace
      - /data:/data
    working_dir: /workspace
    ports:
      - "${HOST_BACKEND_PORT}:3000"


